import { NextResponse } from "next/server";
import nodemailer from "nodemailer";
import { SENSEI_EMAIL } from "@/lib/seo";
import { renderEmail, renderEmailText } from "@/lib/email";
import { BLANK, humanDate, invoiceTotals, type DocValues } from "@/lib/documents";
import { formatRupees, parseAmount } from "@/lib/money";
import { unsign } from "@/lib/sign";

/* "I have paid — please send my receipt." -> Sensei's inbox.

   Built the same way as the admission route beside it: Nodemailer over Gmail
   SMTP, credentials from the environment, Node runtime because Nodemailer needs
   real net/tls.

   The provenance rule is the same one and matters more here, because this email
   is about money. Everything that identifies the invoice — its number, the
   batch, the student it was addressed to, and what it was asking for — is read
   back out of the signed link, never out of the request body. The student can
   only add what Sensei cannot already know: what they say they paid, when, by
   what route, and the reference. So the worst a tampered request can do is
   claim a payment against an invoice Sensei herself issued, which is exactly
   what a WhatsApp message could already do, and she still verifies the money
   before issuing anything.

   Nothing is stored and no document changes. The receipt is generated by hand
   in the admin console afterwards. */
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

/* Per-field caps. Generous for a real answer, small enough that nobody can post
   a megabyte through a form that ends up in a mailbox. */
const LIMITS: Record<string, number> = {
  name: 120,
  email: 200,
  whatsapp: 40,
  amount: 60,
  paidDate: 40,
  method: 40,
  reference: 120,
  note: 800,
};

function clean(v: unknown, max: number) {
  return typeof v === "string" ? v.trim().slice(0, max) : "";
}

/* Header injection guard: a newline inside a header value can append headers of
   the sender's choosing. Subject and Reply-To are built from student input. */
function oneLine(s: string) {
  return s.replace(/[\r\n]+/g, " ").trim();
}

function dash(s: string) {
  return s || "—";
}

function nice(s: string) {
  return s ? humanDate(s) : "";
}

export async function POST(req: Request) {
  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Malformed request." }, { status: 400 });
  }

  // Honeypot: invisible to a person, so anything in it is a bot. Answer 200 so
  // the bot believes it worked and does not retry.
  if (clean(body.company, 100)) return NextResponse.json({ ok: true });

  /* Provenance. The link must be one this server issued, for an invoice. */
  const token = clean(body.token, 4000);
  const payload = unsign<{ t?: string; v?: DocValues }>(token);
  if (!payload || payload.t !== "invoice") {
    return NextResponse.json(
      { ok: false, error: "This invoice link is no longer valid. Please ask Sensei for a fresh one." },
      { status: 400 },
    );
  }
  const inv: DocValues = payload.v && typeof payload.v === "object" ? payload.v : {};

  const f: Record<string, string> = {};
  for (const [key, max] of Object.entries(LIMITS)) f[key] = clean(body[key], max);

  /* Validated here, not only in the browser. Only two things are required: a
     name to put on the receipt, and an address to send it to. */
  if (!f.name) {
    return NextResponse.json({ ok: false, error: "Please add your name." }, { status: 400 });
  }
  if (!EMAIL_RE.test(f.email)) {
    return NextResponse.json(
      { ok: false, error: "That email address does not look right." },
      { status: 400 },
    );
  }

  const user = process.env.GMAIL_USER;
  const pass = process.env.GMAIL_APP_PASSWORD;
  const to = process.env.CONTACT_TO || user;

  if (!user || !pass) {
    console.error("[receipt-request] GMAIL_USER / GMAIL_APP_PASSWORD are not set");
    return NextResponse.json(
      { ok: false, error: `Email is not connected yet. Please write to ${SENSEI_EMAIL}.` },
      { status: 503 },
    );
  }

  const host = process.env.SMTP_HOST;
  const transporter = nodemailer.createTransport(
    host
      ? {
          host,
          port: Number(process.env.SMTP_PORT || 587),
          secure: process.env.SMTP_SECURE === "true",
          auth: process.env.SMTP_NOAUTH === "true" ? undefined : { user, pass },
          tls: { rejectUnauthorized: process.env.SMTP_INSECURE !== "true" },
        }
      : { service: "gmail", auth: { user, pass } },
  );

  /* The same arithmetic the invoice itself printed, so the two figures Sensei
     compares — asked for, and says they paid — are read the same way. */
  const totals = invoiceTotals(inv);
  const invoiceNo = inv.invoiceNo?.trim() || BLANK;
  const asked =
    totals.due !== null && totals.due > 0
      ? formatRupees(totals.due)
      : totals.total !== null
        ? `${formatRupees(totals.total)} (nothing outstanding on the invoice)`
        : "—";

  /* Shown with a rupee sign when it is a figure, and exactly as typed when it
     is not — a student may well write "the second instalment" in that box, and
     rewriting it would lose what they said. */
  const saidPaidNum = parseAmount(f.amount);
  const saidPaid = saidPaidNum !== null ? formatRupees(saidPaidNum) : f.amount || "Not stated";

  const sections: Array<{ title: string; rows: Array<[string, string]> }> = [
    {
      title: "The invoice",
      rows: [
        ["Invoice no.", invoiceNo],
        ["Dated", dash(nice(inv.issueDate?.trim() || ""))],
        ["Billed to", dash(inv.studentName?.trim() || "")],
        ["Batch", dash(inv.batch?.trim() || "")],
        ["Status on the invoice", dash(totals.status)],
        ["Amount it was asking for", asked],
      ],
    },
    {
      title: "What the student says they paid",
      rows: [
        ["Date paid", dash(nice(f.paidDate))],
        ["Paid by", dash(f.method)],
        ["Reference / transaction ID", dash(f.reference)],
      ],
    },
    {
      title: "Send the receipt to",
      rows: [
        ["Name for the receipt", f.name],
        ["Email", f.email],
        ["WhatsApp", dash(f.whatsapp)],
      ],
    },
  ];

  if (f.note) sections.push({ title: "Their note", rows: [["In their words", f.note]] });

  const doc = {
    eyebrow: "Payment",
    title: "Receipt requested",
    subtitle: `${f.name} says they have paid invoice ${invoiceNo} and would like a receipt.`,
    highlight: { label: "Amount they say they paid", value: saidPaid },
    sections,
    footNote:
      "This is a request, not a confirmation: the website has not checked that any money " +
      "arrived and nothing has been marked paid. Check the payment yourself, then generate " +
      `the fee receipt in the admin console and send the link back. Replying to this email writes to ${f.name}.`,
  };

  const text = renderEmailText(doc);
  const html = renderEmail(doc);

  try {
    await transporter.sendMail({
      from: `"Yume Ga Kanau website" <${user}>`,
      to,
      // Reply goes to the address the receipt is wanted at, so Sensei can hit
      // Reply and paste the receipt link straight in.
      replyTo: `"${oneLine(f.name).replace(/"/g, "")}" <${oneLine(f.email)}>`,
      subject: oneLine(`Receipt requested — ${f.name} — invoice ${invoiceNo}`),
      text,
      html,
    });
    return NextResponse.json({ ok: true });
  } catch (err) {
    // Log the message only, never the whole object: `pass` is not on it, but
    // this way it cannot become so by accident.
    console.error("[receipt-request] send failed:", err instanceof Error ? err.message : err);
    return NextResponse.json(
      { ok: false, error: `That did not go through. Please write to ${SENSEI_EMAIL}.` },
      { status: 502 },
    );
  }
}
